//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VChecker
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    [XmlRoot(ElementName = "entry", Namespace = "http://scap.nist.gov/schema/feed/vulnerability/2.0")]
    
    public partial class Entry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entry()
        {
            this.References = new List<References>();
            this.VulnerableConfiguration = new List<VulnerableConfiguration>();
            this.VulnerableSoftwareList = new List<VulnerableSoftwareList>();
        }
    
        [XmlAttribute(AttributeName = "id")]
        public string EntryId { get; set; }
        [XmlElement(ElementName = "summary", Namespace = "http://scap.nist.gov/schema/vulnerability/0.4")]
        public string Summary { get; set; }
        [XmlElement(ElementName = "last-modified-datetime", Namespace = "http://scap.nist.gov/schema/vulnerability/0.4")]
        public string LastmodifiedDateTime { get; set; }
        [XmlElement(ElementName = "published-datetime", Namespace = "http://scap.nist.gov/schema/vulnerability/0.4")]
        public string PublishedDateTime { get; set; }
        public int NvdId { get; set; }
    
        [XmlElement(ElementName = "references", Namespace = "http://scap.nist.gov/schema/vulnerability/0.4")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<References> References { get; set; }
        public virtual Nvd Nvd { get; set; }
        [XmlElement(ElementName = "vulnerable-configuration", Namespace = "http://scap.nist.gov/schema/vulnerability/0.4")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<VulnerableConfiguration> VulnerableConfiguration { get; set; }
        [XmlElement(ElementName = "vulnerable-software-list", Namespace = "http://scap.nist.gov/schema/vulnerability/0.4")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<VulnerableSoftwareList> VulnerableSoftwareList { get; set; }
    }
}
