//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VChecker
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    [XmlRoot(ElementName = "logical-test", Namespace = "http://cpe.mitre.org/language/2.0")]
    
    public partial class LogicalTest2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogicalTest2()
        {
            this.FactRef2 = new List<FactRef2>();
        }
    
        public int LogicalTest2Id { get; set; }
        [XmlAttribute(AttributeName = "negate")]
        public string Negate2 { get; set; }
        [XmlAttribute(AttributeName = "operator")]
        public string Operator2 { get; set; }
        public int LogicalTest1Id { get; set; }
    
        public virtual LogicalTest1 LogicalTest1 { get; set; }
        [XmlElement(ElementName = "fact-ref", Namespace = "http://cpe.mitre.org/language/2.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<FactRef2> FactRef2 { get; set; }
    }
}
