//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VChecker
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    [XmlRoot(ElementName = "logical-test", Namespace = "http://cpe.mitre.org/language/2.0")]
   
    public partial class LogicalTest1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogicalTest1()
        {
            this.FactRef1 = new List<FactRef1>();
            this.LogicalTest2 = new List<LogicalTest2>();
        }
    
        public int LogicalTest1Id { get; set; }
        [XmlAttribute(AttributeName = "negate")]
        public string Negate1 { get; set; }
        [XmlAttribute(AttributeName = "operator")]
        public string Operator1 { get; set; }
        public int VulnerableConfigurationId { get; set; }
    
        [XmlElement(ElementName = "fact-ref", Namespace = "http://cpe.mitre.org/language/2.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<FactRef1> FactRef1 { get; set; }
        [XmlElement(ElementName = "logical-test", Namespace = "http://cpe.mitre.org/language/2.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<LogicalTest2> LogicalTest2 { get; set; }
        public virtual VulnerableConfiguration VulnerableConfiguration { get; set; }
    }
}
