//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VChecker
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    [XmlRoot(ElementName = "references", Namespace = "http://scap.nist.gov/schema/vulnerability/0.4")]
    
    public partial class References
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public References()
        {
            this.Reference = new List<Reference>();
        }
    
        public int ReferencesId { get; set; }
        [XmlAttribute(AttributeName = "lang", Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string Lang { get; set; }
        [XmlAttribute(AttributeName = "reference_type")]
        public string ReferenceType { get; set; }
        public string EntryId { get; set; }
        [XmlElement(ElementName = "source", Namespace = "http://scap.nist.gov/schema/vulnerability/0.4")]
        public string Source { get; set; }
    
        public virtual Entry Entry { get; set; }
        [XmlElement(ElementName = "reference", Namespace = "http://scap.nist.gov/schema/vulnerability/0.4")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Reference> Reference { get; set; }
    }
}
