//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VChecker
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    [XmlRoot(ElementName = "vulnerable-software-list", Namespace = "http://scap.nist.gov/schema/vulnerability/0.4")]
    public partial class VulnerableSoftwareList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VulnerableSoftwareList()
        {
            this.Product = new List<Product>();
        }
    
        public int VulnerableSoftwareListId { get; set; }
        public string EntryId { get; set; }
    
        [XmlElement(ElementName = "product", Namespace = "http://scap.nist.gov/schema/vulnerability/0.4")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Product> Product { get; set; }
        public virtual Entry Entry { get; set; }
    }
}
