//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VChecker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entry()
        {
            this.References = new HashSet<References>();
            this.VulnerableConfiguration = new HashSet<VulnerableConfiguration>();
            this.VulnerableSoftwareList = new HashSet<VulnerableSoftwareList>();
        }
    
        public string EntryId { get; set; }
        public string Summary { get; set; }
        public string LastmodifiedDateTime { get; set; }
        public string PublishedDateTime { get; set; }
        public string NvdPubDate { get; set; }
    
        public virtual Nvd Nvd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<References> References { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VulnerableConfiguration> VulnerableConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VulnerableSoftwareList> VulnerableSoftwareList { get; set; }
    }
}
