//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VChecker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container1 : DbContext
    {
        public Model1Container1()
            : base("name=Model1Container1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entry> EntrySet { get; set; }
        public virtual DbSet<References> ReferencesSet { get; set; }
        public virtual DbSet<VulnerableSoftwareList> VulnerableSoftwareListSet { get; set; }
        public virtual DbSet<VulnerableConfiguration> VulnerableConfigurationSet1 { get; set; }
        public virtual DbSet<LogicalTest1> LogicalTest1Set { get; set; }
        public virtual DbSet<Nvd> NvdSet { get; set; }
        public virtual DbSet<Reference> ReferenceSet { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<FactRef2> FactRef2Set { get; set; }
        public virtual DbSet<LogicalTest2> LogicalTest2Set { get; set; }
        public virtual DbSet<FactRef1> FactRef1Set { get; set; }
    }
}
