//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VChecker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container1 : DbContext
    {
        public Model1Container1(string pathToDb) : base(Checker.getConnectionString("Model1Container1", pathToDb))
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entry> EntrySet { get; set; }
        public virtual DbSet<References> ReferencesSet { get; set; }
        public virtual DbSet<VulnerableSoftwareList> VulnerableSoftwareListSet { get; set; }
        public virtual DbSet<VulnerableConfiguration> VulnerableConfigurationSet1 { get; set; }
        public virtual DbSet<LogicalTest1> LogicalTest1Set { get; set; }
        public virtual DbSet<Nvd> NvdSet { get; set; }
        public virtual DbSet<Reference> ReferenceSet { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<FactRef2> FactRef2Set { get; set; }
        public virtual DbSet<LogicalTest2> LogicalTest2Set { get; set; }
        public virtual DbSet<FactRef1> FactRef1Set { get; set; }
    }
}
