//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VChecker
{
    using System;
    using System.Collections.Generic;
    
    public partial class References
    {
        public int Id { get; set; }
        public string Href { get; set; }
        public string EntryId { get; set; }
    
        public virtual Entry Entry { get; set; }
    }
}
