//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VChecker
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    [XmlRoot(ElementName = "vulnerable-configuration", Namespace = "http://scap.nist.gov/schema/vulnerability/0.4")]
    
    public partial class VulnerableConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VulnerableConfiguration()
        {
            this.LogicalTest1 = new List<LogicalTest1>();
        }
    
        public int VulnerableConfigurationId { get; set; }
        public string EntryId { get; set; }
    
        public virtual Entry Entry { get; set; }
        [XmlElement(ElementName = "logical-test", Namespace = "http://cpe.mitre.org/language/2.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<LogicalTest1> LogicalTest1 { get; set; }
    }
}
